title: "First Baptist Church Muncie"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fbcmuncie.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter: fbcmuncie
facebook: firstbaptistmuncie
flickr: fbcmuncie
youtube: fbcmunciesermons
phone: 765-284-7749